package com.example.bloodbank

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.bloodbank.Model.DonationCenter
import com.example.bloodbank.repository.DonationCenterRepository
import com.example.bloodbank.repository.Result
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.collectLatest
import kotlinx.coroutines.flow.onCompletion
import kotlinx.coroutines.flow.onStart
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class DonationCentersViewModel @Inject constructor(
    private val donationCenterRepository: DonationCenterRepository
) : ViewModel() {

    private val _centers = MutableStateFlow<List<DonationCenter>>(emptyList())
    val centers: StateFlow<List<DonationCenter>> = _centers.asStateFlow()

    private val _isLoading = MutableStateFlow(false)
    val isLoading: StateFlow<Boolean> = _isLoading.asStateFlow()

    private val _error = MutableSharedFlow<String>()
    val error: SharedFlow<String> = _error.asSharedFlow()

    private val _addCenterSuccess = MutableSharedFlow<Unit>()
    val addCenterSuccess: SharedFlow<Unit> = _addCenterSuccess.asSharedFlow()

    init {
        loadDonationCenters()
    }

    fun loadDonationCenters() {
        viewModelScope.launch {
            donationCenterRepository.getDonationCenters()
                .onStart { _isLoading.value = true }
                .catch { e ->
                    _error.emit(e.message ?: "Unknown error loading donation centers")
                    _isLoading.value = false // Ensure loading state is reset on error
                }
                .onCompletion { _isLoading.value = false }
                .collectLatest { result ->
                    when (result) {
                        is Result.Success -> {
                            _centers.value = result.data.orEmpty().sortedByDescending { it.createdAt ?: 0L }
                        }
                        is Result.Error -> {
                            _error.emit(result.exception.message ?: "Failed to load donation centers")
                        }
                    }
                }
        }
    }

    fun addDonationCenter(
        name: String,
        address: String,
        phone: String,
        email: String,
        latitude: Double,
        longitude: Double,
        operatingHours: String,
        maxDailyAppointments: Int,
        isActive: Boolean
    ) {
        viewModelScope.launch {
            _isLoading.value = true
            val newCenter = DonationCenter(
                centerId = null, // ID will be generated by Firebase
                name = name,
                address = address,
                phone = phone,
                email = email,
                latitude = latitude,
                longitude = longitude,
                operatingHours = operatingHours,
                maxDailyAppointments = maxDailyAppointments,
                isActive = isActive,
                createdAt = System.currentTimeMillis() // Add creation timestamp
            )

            donationCenterRepository.addDonationCenter(newCenter)
                .collectLatest { result ->
                    _isLoading.value = false
                    when (result) {
                        is Result.Success -> {
                            _addCenterSuccess.emit(Unit)
                            // Reload centers if not already real-time, or if new data needs to be reflected immediately
                            // loadDonationCenters()
                        }
                        is Result.Error -> {
                            _error.emit(result.exception.message ?: "Failed to add donation center")
                        }
                    }
                }
        }
    }
}