package com.example.bloodbank

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.bloodbank.Model.DonationCenter
import com.example.bloodbank.repository.DonationCenterRepository
import com.example.bloodbank.repository.Result
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.collectLatest
import kotlinx.coroutines.flow.onCompletion
import kotlinx.coroutines.flow.onStart
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class DonationCentersViewModel @Inject constructor(
    private val donationCenterRepository: DonationCenterRepository
) : ViewModel() {

    private val _centers = MutableStateFlow<List<DonationCenter>>(emptyList())
    val centers: StateFlow<List<DonationCenter>> = _centers.asStateFlow()

    private val _isLoading = MutableStateFlow(false)
    val isLoading: StateFlow<Boolean> = _isLoading.asStateFlow()

    private val _error = MutableSharedFlow<String>()
    val error: SharedFlow<String> = _error.asSharedFlow()

    private val _addCenterResult = MutableSharedFlow<Result<Unit>>()
    val addCenterResult: SharedFlow<Result<Unit>> = _addCenterResult.asSharedFlow()

    init {
        loadDonationCenters()
    }

    fun loadDonationCenters() {
        viewModelScope.launch {
            donationCenterRepository.getAllDonationCenters()
                .onStart { _isLoading.value = true }
                .catch { e ->
                    _error.emit(e.message ?: "Unknown error loading donation centers")
                }
                .onCompletion { _isLoading.value = false }
                .collectLatest { centersList ->
                    _centers.value = centersList.sortedByDescending { it.createdAt }
                }
        }
    }

    fun addDonationCenter(name: String, address: String, phone: String, email: String, city: String) {
        viewModelScope.launch {
            _isLoading.value = true
            val newCenter = DonationCenter(
                id = null, // ID will be generated by Firestore
                name = name,
                address = address,
                phone = phone,
                email = email,
                city = city,
                createdAt = System.currentTimeMillis()
            )

            val result = donationCenterRepository.addDonationCenter(newCenter)
            _addCenterResult.emit(result)
            _isLoading.value = false

            if (result is Result.Success) {
                // Optionally reload centers to reflect the new addition if not already real-time
                // loadDonationCenters()
            } else if (result is Result.Error) {
                _error.emit(result.exception.message ?: "Failed to add donation center")
            }
        }
    }
}